name: Build Site

on:
  issues:
    types:
      - opened

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0             
      - name: Checkout submodules
        run: git clone https://github.com/jeffvli/feishin.git
      - name: Install Node and PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install dependencies
        working-directory: ./feishin
        run: pnpm install
      - name: Build Site
        working-directory: ./feishin
        run: pnpm run build:web
        
      - name: Copy Site
        run: cp -afr ./feishin/out/web ./static
      - name: Del Feishin
        run: rm -rf feishin
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.API_TOKEN }}
